### ISSUE TITLE
rename opc_compute_ip_network fails with 404 error

### ISSUE THREAD

**Issue by scross01** [terraform-providers/terraform-provider-opc#75] opened 2017-08-31 12:53 UTC
### Terraform Version
terraform v0.10.2
opc_provider v0.1.2

### Affected Resource(s)
- opc_compute_ip_network

### Terraform Configuration Files
```hcl
resource "opc_compute_ip_network" "example" {
  name = "example-subnet3"
  ip_address_prefix = "192.168.0.0/24"
}
```

### Steps to Reproduce
`terraform apply` rename the resource to `example-subnet4` and `terraform apply` again

### Expected Behavior
The IP Network resource should be destroyed and then recreated with the new name

### Actual Behavior
The provider tries to rename the resouce, but failes

```
$ terraform plan
...
  ~ module.opc_ip_network.opc_compute_ip_network.network[2]
      name: "example-subnet3" => "example-subnet4"
```

```
$ terraform apply
...
module.opc_ip_network.opc_compute_ip_network.network.2: Modifying... (ID: example-subnet3)
  name: "example-subnet3" => "example-subnet4"
Error applying plan:

1 error(s) occurred:

* module.opc_ip_network.opc_compute_ip_network.network[2]: 1 error(s) occurred:

* opc_compute_ip_network.network.2: Error updating IP Network 'example-subnet4': 404: {"message": "no IpNetwork object named /Compute-usorclptsc53098/stephen.cross@oracle.com/example-subnet4 found"}
```

**Comment by grubernaut** [comment] 2017-08-31 13:45
Hey @scross01 this is a duplicate of #71, and has been fixed in #73. 
This should be released in the next version of the provider, which is currently slotted for `v0.1.3`, however, we would like to bump that release version to `v1.0.0` to better follow with semver. I believe some marketing material is needed for that version bump, however, so we can release `v0.1.3` now if this change is desperately needed. Thanks!

**Closed by grubernaut** 2017-08-31 13:45 UTC
Labels: bug

**Comment by scross01** [comment] 2017-08-31 13:48
thanks @grubernaut - I should have checked the fixed issues first :-) I had a recollection I had encounter the error before.

**Comment by grubernaut** [comment] 2017-08-31 13:49
No worries! :smile:
