### ISSUE TITLE
Creating additional opc compute instances will destroy the existing compute instances

### ISSUE THREAD

**Issue by ubersol** [terraform-providers/terraform-provider-opc#39] opened 2017-07-18 22:20 UTC
Hi there,

I am running into an issue where I can create multiple opc compute instances just fine, but when I want to add additional compute instances, the execution plan destroys all previously created machines and redeploys the new instances. 

### Terraform Version
[deniz@lem]$ terraform -v
Terraform v0.9.11

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume
- I think this is also resource independent because during new instance creation, everything else gets destroyed

### Terraform Configuration Files
I have divided the configuration files in smaller pieces in my environment

```hcl
_**main.tf**_
data "template_file" "userdata" {
  template = <<JSON
{
  "userdata": {
    "pre-bootstrap": {
      "script": [
        "( echo n;echo p;echo 1;echo; echo; echo w;) | sudo fdisk /dev/xvdb",
        "sudo mkfs -t ext3 /dev/xvdb",
        "sudo mkdir /mnt/store",
        "sudo mount /dev/xvdb /mnt/store",
        "sudo chown -R opc:opc /mnt/store/",
        "echo '/dev/xvdb /mnt/store ext3 defaults 1 2' | sudo tee -a /etc/fstab"
      ]
    }
  }
}
JSON
}

resource "opc_compute_ip_reservation" "ipreservation" {
  count       = "${var.instance_count}"
  parent_pool = "/oracle/public/ippool"
  permanent   = true
}


resource "opc_compute_storage_volume" "data" {
  count = "${var.instance_count}"
  name  = "data-${count.index}"
  size  = 10
}

resource "opc_compute_instance" "test" {
  count      = "${var.instance_count}"
  name       = "deniz-test-instance-${count.index}"
  label      = "Terraform Provisioned Instance"
  shape      = "oc3"
  image_list = "/oracle/public/OL_6.8_UEKR3_x86_64"

  ssh_keys            = ["${opc_compute_ssh_key.test.name}"]
  instance_attributes = "${data.template_file.userdata.rendered}"

  storage {
    volume = "${element(opc_compute_storage_volume.data.*.id, count.index)}"
    index  = 1
  }

  networking_info {
    index          = 0
    shared_network = true
    nat            = ["${element(opc_compute_ip_reservation.ipreservation.*.id, count.index)}"]
  }
}

output "public_ip" {
  value = "${opc_compute_ip_reservation.ipreservation.*.ip}"
}
```

```hcl
secrule.tf

#secrules, seclists, sec associations

resource "opc_compute_sec_rule" "ssh-vm-secrule" {
  name             = "ssh-vm-secrule"
  source_list      = "seciplist:${opc_compute_security_ip_list.public_internet.name}"
  destination_list = "seclist:${opc_compute_security_list.allow-ssh-access.name}"
  action      = "permit"
  application = "${opc_compute_security_application.all.name}"
}

resource "opc_compute_security_application" "all" {
  name     = "all"
  protocol = "tcp"
  dport    = "22"
}

resource "opc_compute_security_ip_list" "public_internet" {
  name       = "public_internet"
  ip_entries = ["0.0.0.0/0"]
}

resource "opc_compute_security_list" "allow-ssh-access" {
  name                 = "allow-ssh-access"
  policy               = "deny"
  outbound_cidr_policy = "permit"
}

resource "opc_compute_security_association" "associate_SSH" {
  name = "${format("associate_SSH%1d", count.index + 1)}"
  count   = "${var.instance_count}"
  vcable  = "${element(opc_compute_instance.test.*.vcable,count.index)}"
  seclist = "${element(opc_compute_security_list.allow-ssh-access.*.name,count.index)}"
}
```

```hcl
ssh.tf

resource "opc_compute_ssh_key" "test" {
  name    = "test-key"
  key     = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD05YI38Nwd79pWwuEEUGwcnVPzP2/EodeAkzQtmPa9S4KnDS2bAib2GkRkE8TVA/vZWkavfySaTab+TpBsZvf5r/YfqsK2gsRqyPxi+0G/bD92daBuHpHUlKZ55/qJsI5cSEbSmi5j1PAMiomW9DQzddJ8WX6TNdO1KDfRdQBYTN+br0sbl9K9QvxqqkQ0xKI5VwpEJPKSrx6onjQkUIcPUjfPQsCJMts1sW9pBpFdjoTf8Xm/49MPbcru1Sxs/8srsfEt8AHZcZxmKT6pqfdc4Sb+lIRPiba7J8/QGef1uD00BxOKjNtBMxWGilyv5ogZEwki8BsLGUWz6nttEbIzGkPio1ZqX+cCx5TItYoBHcf7DZD1Foa6T4tR2TH13791cWQbKjDc1vthVDu/fZ7BbVGsyeHEHEmh9uTQ7t6Bq8UHeTWKTSIh7RWanFKBeLMZHajZ/hcxS3tSdmDethjE0OyxBtZn8r8zTKIufjQEHaoqRbKDN/ezRfoi0/ocxenldSOjt3PlE1QvbIuSLtMYRxU4eWVRt/w55+dYhUDQ6uVRITLM3gKnI5o98DUO0bKrargADWpOu4vNZA3uhbN5z5GbLxdMNAKMcVophFYb1cXk6DktW+NA4KDQ0cf7Sp4McyClOhBVjSflPrRu1Dq/tWPPxjIYhBzIfCMgAabuyw== rwzfs0@gmail.com"
  enabled = true
}
```

### Debug Output
There are no errors created per se, but I am going to point to plan and apply gist for the record.

terraform plan and apply - initial two instances
https://gist.github.com/ubersol/1ea39805757f43d611c87948cb77c638

terraform plan and apply - additional three instances
https://gist.github.com/ubersol/3fb8210cb167acf6dce39e2a8396f86e

### Panic Output
No panic

### Expected Behavior
After executing the plan for the additional three instances, I should end up a total of 5 machines.

### Actual Behavior
Terraform is able to create my initial two instances without any problem, however after re-executing the plan for three more instances, terraform deleted all of my machines and its resources.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

First Plan couple machines
1. `terraform plan -var instance_count=2`
Then execute the plan
2. `terraform apply -var instance_count=2`
This gets executed fine in a fresh environment, no problem. Then proceed to plan and execute for three more machines
3. `terraform plan -var instance_count=3`
4. `terraform apply -var instance_count=3`

Steps 3 & 4 forces to destroy the machines created in Steps 1 & 2. The outputs can be seen in the gists mentioned above

### Important Factoids
I am running this for OPC ( oracle public cloud ) and using terraform-provider-opc provider.

### References
Not sure!

**Comment by scross01** [comment] 2017-07-19 13:13
Looks like a bug, something odd is happening with the processing the `networking_info` and `storage` blocks on the 2nd apply when using counts that is forcing the instances to be recreated

```
    networking_info.#:                            "1" => "1"
    networking_info.4151863384.index:             "0" => "0"
    networking_info.4151863384.ip_address:        "" => ""
    networking_info.4151863384.ip_network:        "" => ""
    networking_info.4151863384.name_servers.#:    "0" => "0"
    networking_info.4151863384.nat.#:             "1" => "0" (forces new resource)
    networking_info.4151863384.nat.0:             "cfb6ac34-c77e-45e8-bd9d-83bc0ebb02bf" => "" (forces new resource)
    networking_info.4151863384.search_domains.#:  "0" => "0"
    networking_info.4151863384.shared_network:    "true" => "false" (forces new resource)
    networking_info.4151863384.vnic:              "" => ""
    networking_info.4151863384.vnic_sets.#:       "0" => "0"
    networking_info.~4103242853.dns.#:            "" => "<computed>" (forces new resource)
    networking_info.~4103242853.index:            "" => "0" (forces new resource)
    networking_info.~4103242853.ip_address:       "" => ""
    networking_info.~4103242853.ip_network:       "" => ""
    networking_info.~4103242853.mac_address:      "" => "<computed>" (forces new resource)
    networking_info.~4103242853.name_servers.#:   "" => "0"
    networking_info.~4103242853.nat.#:            "" => "<computed>" (forces new resource)
    networking_info.~4103242853.search_domains.#: "" => "0"
    networking_info.~4103242853.sec_lists.#:      "" => "<computed>" (forces new resource)
    networking_info.~4103242853.shared_network:   "" => "true" (forces new resource)
    networking_info.~4103242853.vnic:             "" => ""
    networking_info.~4103242853.vnic_sets.#:      "" => "0"
```

```
    storage.#:                                    "1" => "1"
    storage.2331833218.index:                     "1" => "0" (forces new resource)
    storage.2331833218.volume:                    "data-0" => "" (forces new resource)
    storage.~3359052495.index:                    "" => "1" (forces new resource)
    storage.~3359052495.name:                     "" => "<computed>"
    storage.~3359052495.volume:                   "" => "${element(opc_compute_storage_volume.data.*.id, count.index)}" (forces new resource)
```

**Comment by scross01** [comment] 2017-07-19 21:28
@ubersol the security list issue (see #17) is already fixed in the master branch. 

The workaround is to explicitly set the `policy` and `outbound_cidr_policy` as `PERMIT` or `DENY` (i.e. use uppercase) in the .tf config

**Comment by grubernaut** [comment] 2017-07-19 22:15
Hi @ubersol, thanks for the issue!

And also, apologies for getting back to you so late with a response. 

The core issue here is the use of `element()`. As a general rule, we recommend that users not use `element` for indexing arrays, unless they specifically need to benefit from the modulo features of `element`. Otherwise, we recommend to just use the `[]` syntax to index an array. 

I wrote up a reproduction case for your Terraform config and was able to confirm that the issue is no longer happening while using `[]` instead of `element()`. 

```
resource "opc_compute_ip_reservation" "ipreservation" {
  count       = "${var.instance_count}"
  parent_pool = "/oracle/public/ippool"
  permanent   = true
}


resource "opc_compute_storage_volume" "data" {
  count = "${var.instance_count}"
  name  = "data-${count.index}"
  size  = 10
}

resource "opc_compute_instance" "test" {
  count      = "${var.instance_count}"
  name       = "deniz-test-instance-${count.index}"
  label      = "Terraform Provisioned Instance"
  shape      = "oc3"
  image_list = "/oracle/public/OL_6.8_UEKR3_x86_64"

  ssh_keys            = ["${opc_compute_ssh_key.test.name}"]
  instance_attributes = "${data.template_file.userdata.rendered}"

  storage {
    volume = "${opc_compute_storage_volume.data.*.id[count.index]}"
    index  = 1
  }

  networking_info {
    index          = 0
    shared_network = true
    nat            = ["${opc_compute_ip_reservation.ipreservation.*.id[count.index]}"]
  }
}
```

Happy to help out further if you experience any other issues. Thanks!

**Closed by grubernaut** 2017-07-19 22:15 UTC
Labels: bug

**Comment by ubersol** [comment] 2017-07-20 17:39
Hi @grubernaut , yes thank you for that suggestion and that works.... Unfortunately I am running into a different issue now where I will open a new bug/issue...Thanks again for all of your help!!
